# Generated by Django 5.1.1 on 2024-09-25 03:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=128)),
                ('password_salt', models.CharField(max_length=32)),
                ('timezone', models.CharField(default='UTC', max_length=128)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'db_table': 'session',
            },
        ),
    ]
